#!/bin/bash


### Vicon datastream SDK ###
# Installs the Vicon Datastream SDK
# Which involves copying the library and corresponding headers

echo "Installing Vicon datastream SDK..."

echo "Copying libViconDataStreamSDK_CPP.so to /usr/lib/..."
cp vicon_datastream_sdk/libViconDataStreamSDK_CPP.so /usr/lib/

cd vicon_datastream_sdk
for FILE in libboost_*; do
	echo "Copying $FILE to /usr/lib/...";
	cp $FILE /usr/lib/
done
cd ../

echo "Copying DataStreamClient.h to /usr/include/..."
cp vicon_datastream_sdk/DataStreamClient.h /usr/include/

echo "Copying IDataStreamClientBase.h to /usr/include/..."
cp vicon_datastream_sdk/IDataStreamClientBase.h /usr/include/

echo "Installation succesful!"
