#!/bin/bash

# Set script directory
DIR=$(dirname "$(realpath "$BASH_SOURCE[0]")")

# Export PRU_CGT so the makefiles know where the PRU compiler is located
# And make it persistent by adding it to ~/.bashrc of the user
echo "Exporting PRU_CGT..."
COMMAND="export PRU_CGT=$DIR/compiler"
eval "$COMMAND"
grep -qF -- "$COMMAND" ~/.bashrc || echo "$COMMAND" >> ~/.bashrc

