#!/bin/bash

# Set script directory
DIR=$(dirname "$(realpath "$BASH_SOURCE[0]")")

# Export PRU_CGT so the makefiles know where the PRU compiler is located
# And make it persistent by adding it to ~/.bashrc of the user
echo "Exporting PRU_CGT..."
COMMAND="export PRU_CGT=$DIR/pru-cgt"
eval "$COMMAND"
grep -qF -- "$COMMAND" ~/.bashrc || echo "$COMMAND" >> ~/.bashrc

# Export PRU_ICSS so the makefiles know where the PRU ICSS files are located
# And make it persistent by adding it to ~/.bashrc of the user
echo "Exporting PRU_ICSS..."
COMMAND="export PRU_ICSS=$DIR/pru-icss"
eval "$COMMAND"
grep -qF -- "$COMMAND" ~/.bashrc || echo "$COMMAND" >> ~/.bashrc