#!/bin/bash

# Get directory of script
DIR="$( cd "$( dirname "$0" )" && pwd )"

# Call cmake
cmake -B"$DIR/build" -H"$DIR" -DCMAKE_TOOLCHAIN_FILE=toolchain-arm-linux-gnueabihf.cmake

# Call make
make -C $DIR/build --no-print-directory
